In [3]:
import numpy as np

##### Practice# 1 --------> Create a numpy array with 0s and 1

###### import Packages

In [4]:
#nArray=np.empty(64)
L1 = list(range(1,65))
for i in range(len(L1)):
    if i%2==0:
        L1[i]=0
    else:
        L1[i]=1
nArray=np.array(L1)
nArray=nArray.reshape((8,8))
print(nArray)

[[0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0 1]]


##### Practice# 2 --------> reshape the np array to single Dimension

In [7]:
nArray=nArray.flatten()
print(nArray)

[0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0
 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1]


##### Practice# 3 --------> reshape the np array to single Column

In [12]:
nArray=nArray.reshape(-1,1)
print(nArray)
print(nArray.shape)

[[0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]]
(64, 1)


##### Create an random array and replace greater than 10 with 10 

In [20]:
np.random.seed(2)
mArray=np.random.randint(100,size=(10,10))
print(f"our array at first step \n {mArray}")
for i in range(mArray.shape[0]):
    for j in range(mArray.shape[1]):
        if mArray[i,j]>10:
            mArray[i,j]=10
        else:
            pass
print(f"\n our array after changes \n {mArray}")

our array at first step 
 [[40 15 72 22 43 82 75  7 34 49]
 [95 75 85 47 63 31 90 20 37 39]
 [67  4 42 51 38 33 58 67 69 88]
 [68 46 70 95 83 31 66 80 52 76]
 [50  4 90 63 79 49 39 46  8 50]
 [15  8 17 22 73 57 90 62 83 96]
 [43 32 26  8 76 10 40 34 60  9]
 [70 86 70 19 56 82  1 68 40 81]
 [61 70 97 18 84 90 87 22 43 52]
 [74 72 90 99 91 96 16 55 21 43]]

 our array after changes 
 [[10 10 10 10 10 10 10  7 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10  4 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10  4 10 10 10 10 10 10  8 10]
 [10  8 10 10 10 10 10 10 10 10]
 [10 10 10  8 10 10 10 10 10  9]
 [10 10 10 10 10 10  1 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]]
